### ISSUE TITLE
Girilen websitesi algılanmalıdır.

### ISSUE THREAD

**Issue by yigithankardas** [CensorKeepers/FilterAI#5]
Kullanıcıların girdiği internet siteleri Selenium fonksiyonları kullanılarak algılanmalıdır ve algılanan URL'ler depolanmalıdır. 

![image](https://github.com/CensorKeepers/FilterAI/assets/78052319/0c571bdb-f5ab-4a07-81a2-836296dbef0e)

**Comment by hiracansu** [comment]
Kullanıcıların girdiği internet siteleri selenium methotları kullanılarak algılanmalıdır ve algılanan URL'ler depolanmalıdır. Açılan sayfalar driver.window_handles kodu ile elde edilecektir. Açılan her sekme ve içerisinde bulunan url depolanacaktır.

**Comment by hiracansu** [comment]
Açılan sayfalar `driver.window_handles` ile elde edilecektir. Açılan her sekme ve içerisinde bulunan URL depolanacaktır.

Bu görev tamamlandığında dict_items([('tab', 'url')]) şeklinde bir çıktı vermesi beklenmektedir. Bu çıktı elde edildiğinde görev tamamlanmış olacaktır.
