### ISSUE TITLE
CSS değiştirme işlemi yapılmalıdır.

### ISSUE THREAD

**Issue by yigithankardas** [CensorKeepers/FilterAI#7]

**Comment by hiracansu** [comment]
Bulunan toksik içerikli kelimeler CSS ile yöneticinin seçtiği şekilde işlemlerden geçecektir. Örneğin gizlemek istiyorsa gizlenecek veya renkli bi şekilde üstünü çizmek istiyorsa üstü çizilecektir. Bu işlem için Selenium tarafında bir kontrolcü yok fakat CSS değiştirme JavaScript vasıtasıyla yapılabiliyor. Sayfadaki elementlerin yerini belirlemede Selenium kullanılabilir. Ardından bulunan elementlerin stili JavaScript çalıştırılarak değiştirilebilir.
Görev tamamlandığında program bu bahsedilen davranışı gerçekleştirebilecek. Başarılı olarak nitelendirmek içinse elementin stilini JavaScript ile değiştirmek sayılabilir.

![image](https://github.com/CensorKeepers/FilterAI/assets/78052319/9abe8a1e-7b42-4e37-97bd-cc254323a4ac)
