### ISSUE TITLE
Yeni sekme açıldığında ve kapandığında algılanmalıdır.

### ISSUE THREAD

**Issue by yigithankardas** [CensorKeepers/FilterAI#8]
Kullanıcının açtığı her yeni sekme ve her sekmede açılan internet siteleri algılanmalıdır. Ayrıca kapatılan sekmeler veya internet siteleri de kontrol edilmelidir. Bunun için kontrolcü threadler kendi içlerinde her sekme için thread açabilir veya kontrolcü threadler `driver.window_handles` objesini track edebilirler.
Görev tamamlandığında program her yeni sekme için 'Yeni sekme bulundu. URL: <....>' şeklinde çıktı üretebilecek ve üstte bahsedilen yöntemlerin biri kullanılarak özellik eklendiğinde ise görev tamamlanmış sayılacak.

![image](https://github.com/CensorKeepers/FilterAI/assets/78052319/6ef1ddfe-a3f4-43da-92b5-a1d7e1a925f9)

**Comment by hiracansu** [comment]
Yeni sekme açıldığında url'sini algılayan kod feature/8 branchine yazaılmıştır. Kod şimdilik sadece yeni bir sekme açılırsa o sitenin url'sini print ediyor. Bu geliştirilecektir.

**Comment by yigithankardas** [comment]
Yeni sekmeler listeye eklenmeli, kapatıldığında ise çıkarılmalıdır yoksa her seferinde ilk bulduğu yeni sekmeyi tekrar buluyor.

**Comment by yigithankardas** [comment]
Selenium programı ile tarayıcı sekmelerini senkronize etme işi beklediğimizden fazla zor çıktı ve uyguladığımız çözümler işe yaramadı. Uygulanabilir bir çözüm bulana kadar tarayıcıda tek sekme açılmasına izin verecek şekilde programı güncelliyoruz.
