### ISSUE TITLE
URL değiştiğinde ve refresh edildiğinde algılanmalıdır.

### ISSUE THREAD

**Issue by yigithankardas** [CensorKeepers/FilterAI#9]
Kullanıcı herhangi bir sekmeyi yenilediğinde bu algılanmalıdır. Bunun sebebi o site içerisinde bir değişiklik olduysa bunları algılamak ve kontrol etmektir.
Görev tamamlandığında program sekmenin yenilendiğini algılayacak ve filtreleme işlemini tekrar çalıştıracaktır.

**Comment by hiracansu** [comment]
sayfanın navigation start  zamanı ile refresh yapılıp yapılmadığı algılanıyor. Bunu url bulduğumuz sınıf içinde denedim çalışıyor gibi gözlemledim.
